smart-signature/smart-signature-future

package-lock.json, package.json, src/App.vue, src/components/ArticleCard.vue, src/main.js, src/router.js, src/views/Home/ArticlesList.vue, src/views/Home/MyBanner.vue, src/views/Home/index.vue, src/views/Login.vue
feat: ArticleCard now display relative time 
refactor: Breaking `Home` into smaller components 
feat: login page finished, no more auto login request
=> refactor: Breaking `Home` into smaller components 

src/components/AssetCard.vue, src/components/index.js, src/router.js, src/views/Asset.vue, src/views/User.vue
=> Add Asset page & link /w user page

README.md, src/main.js, src/views/Article.vue, src/views/Publish.vue
效果： [底部有代码段落的文章](https://sign-dev.dravatar.xyz/article/QmYbhYLZczxXBdQnb6F7ZhEv4k4dWvP5aUYpt83mvzUV6y)
=> Temp fix: code syntax highlight in article

.eslintrc.js, package-lock.json, public/index.html, src/api/scatter.js, src/api/signature.js, src/components/ArticleCard.vue, src/views/Article.vue, src/views/Asset.vue, src/views/Home/MyBanner.vue, src/views/Home/index.vue, src/views/Login.vue, src/views/Publish.vue, src/views/User.vue
[PR的预览（速度慢，需翻）](https://5c8a0225d9df30000848211a--smasin-dev.netlify.com/)
=> 进入特定 View 自动更新标题，首页设计修改，Auto Linting 之前的代码

src/api/scatter.js, src/api/signature.js, src/views/Article.vue, src/views/Publish.vue
搭配合約的更新
https://github.com/smart-signature/smart-signature-EOS-contract/commit/cbfeeb9eee35001bef5b7bb8e9c9560632514f4e
因為現在的 support 需要新版 sign 的搭配，所以必須經由這版前端的 publish 才能 work
然後，sendThePost 在 call 合約的 publish 之前就報錯了，需要急救
=> Update support & publish

src/api/scatter.js, src/views/Publish.vue
=> Add signature for backend

src/views/Home/index.vue
=> fix publish button align center

src/api/backend.js, src/api/ipfs.js, src/views/Article.vue, src/views/Home/ArticlesList.vue, src/views/Publish.vue
* refactor: disable old API because no one is using it
* fix: HTTPS 模式下因为安全策略无法访问后端(HTTP)
=> refactor: disable old API & fix: bad (http) connection 

src/api/backend.js, src/api/scatter.js, src/api/signature.js, src/main.js, src/views/Article.vue, src/views/Asset.vue, src/views/Home/index.vue, src/views/Publish.vue, src/views/User.vue
=> lint: code clean

src/views/Article.vue
check if amount is float and > 0
=> add Amount check (is float and > 0)

package-lock.json, package.json, src/views/Article.vue
=> get referrer

src/api/signature.js, src/views/Publish.vue, src/views/User/Asset.vue
Feel cool to merge and close #68
=> feat: custom fission_factor

package-lock.json, src/api/signature.js, src/views/Article.vue, src/views/User/Asset.vue, src/zarm.js
=> Add withdraw confirm &  Link withdraw to Asset.vue

package-lock.json, package.json, src/api/backend.js, src/views/Article.vue, src/views/Publish.vue, src/views/User/Asset.vue, src/zarm.js
Testing function mentioned in #63
=> fix: Publish 时检测登录 & fix: 试图使用 HTTPS 接口发文

src/views/Article.vue, src/views/Publish.vue
After merged,  This closes #50.
=> Trying to close my issues

src/views/User/index.vue
Let's close https://github.com/smart-signature/smart-signature-future/issues/82.
=> fix income in user page

src/views/Article.vue, src/views/Publish.vue
=> [OK to APPROVE and MERGE]feat: image upload

src/api/imagesUploader.js, src/api/index.js, src/api/scatter.js, src/views/Article.vue, src/views/Publish.vue
Tested in development mode, ready to merge
=> Refactoring API

src/api/signature.js, src/views/Article.vue
@guanchao71
可以測試此文章有沒有被登錄中的用戶打賞過。
打賞過的話，按鈕會正確被 disable
之前打賞成功的文章都會 work ，不是只有在這之後才打賞的而已
=>  Make isSupported work and great again

src/api/backend.js, src/views/Publish.vue
我還是不知道 this.fissionFactor 值你們有沒有讓他輸入並寫入？
=>  add fissionFactor to publishArticle 

src/components/AssetCard.vue, src/views/User/Asset.vue
=> Fix Asset.vue

package-lock.json, package.json, src/api/backend.js, src/api/signature.js, src/main.js, src/views/Article.vue, src/views/Home/ArticlesList.vue, src/views/Publish.vue
=> feat: scroll to next page in Home View

src/App.vue, src/components/Header.vue, src/components/index.js, src/views/Article.vue
=> Add Header.vue  & fix #96 #109

src/api/backend.js, src/api/scatter.js, src/views/Publish.vue
revert: revert #112 
fix: require login when send
fix: backend need `publickey` but got `publicKey`
=> Testing IN testing BRANCH, REVERT ANY TIME

src/components/AssetCard.vue, src/views/User/Asset.vue, src/views/User/index.vue
=>  set AssetCard Time To LocalTime 

src/api/scatter.js, src/api/signature.js, src/config/network.js, src/views/Article.vue
=> Add totalSupportedAmount in Article.vue

package.json, src/App.vue, src/api/backend.js, src/api/index.js, src/api/signature.js, src/components/AssetCard.vue, src/config/network.js, src/registerServiceWorker.js, src/views/Article.vue, src/views/User/Asset.vue, src/views/User/index.vue
=> 重新编排 npm scripts & 网站 Service Worker 更新提醒

src/views/User/ArticlesList.vue, src/views/User/index.vue
=> add user/original view filter.

src/views/Article.vue, src/views/Home/ArticlesList.vue, src/views/Publish.vue, src/views/User/index.vue
=>  Fix totalSupportedAmount display

src/components/AssetCard.vue, src/views/User/ArticlesList.vue, src/views/User/Asset.vue
资产明细、文章列表 加载完成之后去掉 ‘加载中’
---
Please review
=> 资产明细、文章列表 加载完成之后去掉 ‘加载中’

src/views/User/Asset.vue
=>  Fix bug in #52 

src/api/signature.js, src/views/Article.vue, src/views/User/Asset.vue
之前版本在未获得赞赏状态时，可以快速点击赞赏按钮触发服务器返回500错误，这是不应当的。
=> 前端上修复收入和实际情况不匹配的问题&在未获得赞赏状态时，按钮设为加载中

src/api/signature.js, src/views/Article.vue
=> 修复赞赏按钮在加载中状态时仍然可以点击&增加赞赏金额加载&修复文章页边距的问题

src/views/Home/ArticlesList.vue
=> Update article list mask

src/api/scatter.js
fix a problem that `requiredFields.account` expected object but got array
=> fix: fixing requiredFields

src/views/Publish.vue
=> Fix: fission factor 在用户界面输入框固定 2, 传过去的为 2000

src/store.js
修复查询 EOS 结果显示 当用户没有 EOS 的时候不显示三个 ...
---
before: 
after:
=> 修复查询 EOS 结果显示

src/App.vue, src/components/Header.vue, src/store.js, src/views/About.vue, src/views/Article.vue
打解釋和查證很費時，累
一樣別急著合併，需細看一下
整體重構晚點，除了登陸問題，還有一票功能未完成呢
@IfFlyOverGrass 記得分配今天的工作在 1200 之前，方便其他人開工
=> Renew Header.vue

src/common/methods.js, src/components/AssetCard.vue, src/views/User/Asset.vue, src/views/User/index.vue
=> 修复个人主页收益显示

src/api/backend.js, src/api/index.js, src/views/Article.vue
=> Renew Article.vue's created

src/App.vue, src/api/backend.js, src/components/Header.vue, src/store.js, src/views/Article.vue
被文檔搞了，"添加评论 (need access_token) " 寫的地址和示例是不同的，幸好眼尖有發現不然一整個黑人問號
https://github.com/smart-signature/smart-signature-backend/blob/master/doc.md
=> Hot fix: sendComment work from now

src/views/Article.vue
=> Fix isNaN eslint error

package.json, src/main.js, src/plugins/iview.js, src/store.js, src/views/Article/CommentsList.vue, src/views/Publish.vue
=> Renew wallet detection logic

src/views/Article/index.vue, src/views/User/Asset.vue
=> 更改分享按钮执行顺序、调整格式

src/api/backend.js, src/api/ipfs.js, src/views/Article/CommentsList.vue, src/views/Home/ArticlesList.vue, src/views/User/ArticlesList.vue
=> Standardize API_address to test svr

src/App.vue, src/api/backend.js, src/api/ipfs.js, src/api/signature.js, src/common/methods.js, src/components/AssetCard.vue, src/components/Header.vue, src/components/WangEditor.vue, src/main.js, src/router.js, src/views/Article/CommentsList.vue, src/views/Article/index.vue, src/views/Home/ArticlesList.vue, src/views/Login.vue, src/views/Publish.vue, src/views/User/ArticlesList.vue, src/views/User/Asset.vue, src/views/User/index.vue
调整并消除eslint报错，一些报错局部屏蔽掉了 没有写eslint 规则  这样不用改动太多代码
---
Please Review
=> 调整并消除 eslint 报错

src/api/backend.js
=> 重写一下token的验证方式

README.md, src/api/backend.js
=> 消除eslint报错

.env.development, .env.production, README.md, package.json, src/api/backend.js
=> 区分开发环境和生产环境

src/components/CommentCard.vue
=> fix comment time problem

src/views/Article/index.vue
=> No getSignInfo need

.env.development, .env.production, README.md, src/api/signature.js
解决 CONTRACT_ACCOUNT undefined
---
原因 其他地方使用需要使用 VUE_APP_xxxxx 这样的格式
=> 解决 CONTRACT_ACCOUNT undefined

src/api/backend.js, src/api/scatter.js, src/views/Article/CommentsList.vue, src/views/Article/index.vue, src/views/Publish.vue, src/views/User/index.vue
還有一份 authDemo 待合併
跟 await getAuth 在舊版錢包運作的邏輯好像不太對，沒有 await 到
=> Remove this.sign &  Renew authSignature

src/api/backend.js, src/api/scatter.js, src/components/BaseHeader.vue, src/views/Article/index.vue
主要是 auth 參數大小寫問題
也把 getAuth 換了合理的位置(登錄後)
=> Fix support

src/views/User/index.vue
现在在获取不到账户信息的时候会提示“账号信息无效，...失败”
=> fix unlogined follow/unfollow bug.

src/views/Article/index.vue
=> Add version to title

src/api/signature.js, src/components/AssetCard.vue, src/views/User/Asset.vue
- Fix 'signature.bp' 
- Disable ArticleCard
=> Hot fix: Fix 'signature.bp'

src/views/About.vue, src/views/Article/index.vue
=> 去掉文章title 版本号、修复关于我们header

src/views/Article/index.vue
=> 修复连续调用两次第一页接口

src/components/AssetCard.vue, src/router.js, src/views/User/Asset.vue, src/views/User/DraftBox.vue, src/views/User/FansList.vue, src/views/User/FollowList.vue, src/views/User/index.vue, src/zarm.js
前端的布局页面等已经完成。
功能等后端到位后加上（一起加，反正也不多）。
设计没回我，图标明天再加。
=> add userview frontend basic.

src/App.vue, src/api/signature.js, src/router.js, src/store.js, src/views/Article/index.vue, src/views/Publish.vue, src/views/User/DraftBox.vue, src/views/User/FansList.vue, src/views/User/FollowList.vue, src/views/User/Original.vue, src/views/User/Reward.vue
Reason: https://juejin.im/post/5bfa4bb951882558ae3c171e
=> No more async created()

src/api/backend.js, src/views/User/index.vue
=> Update new version for access token process

src/components/ArticleCard.vue, src/router.js, src/views/Article/index.vue, src/views/Publish.vue
=> 支持hash查询文章

src/views/User/index.vue
现在昵称重复会正确提示昵称已存在。
现在不会再发生排版错误了。
=> fix 500 bug, css bug.

src/api/backend.js, src/api/scatter.js
- Fix "decodedData is null" in getAuth
- Renew getArbitrarySignature
- Merge currentEOSAccount & API.getAccount()
=> Fix bug in getAuth

src/views/Article/index.vue
现在会处理列表并正确切换赞赏按钮状态。
基本不会出现重复打赏的可能了……吧？（只要不在这个页面瞎玩钱包登录/退出）
#298
=> fix article page tip bug.

package.json, src/api/backend.js, src/views/User/index.vue
=> Fix getUser bug

package.json, src/api/backend.js, src/api/index.js, src/router.js, src/views/Article/index.vue, src/views/Home/MyBanner.vue, src/views/Publish.vue, src/views/User/Asset.vue, src/views/User/AvatarUploader.vue, src/views/User/FollowList.vue, src/views/User/css/cropper.css, src/views/User/index.vue
https://github.com/smart-signature/smart-signature-future/issues/216
=> upload avatar

package.json, src/api/backend.js, src/views/User/index.vue
#370 done
2019 ，沒有 Promise 的 request 必須被棄用
對照過前後版本發送的請求也做過功能測試，應該沒問題。
有問題請回報，速修。
=> Remove request

.editorconfig, package.json, src/api/backend.js, src/views/Publish.vue, src/views/User/FollowList.vue, src/views/User/index.vue
修复了eslint检测出的错误
增加了通过滑块调整裂变系数的功能。
https://github.com/smart-signature/smart-signature-future/issues/319
=> 修复格式错误与通过滑块设置裂变系数

src/views/Publish.vue
https://github.com/smart-signature/smart-signature-future/issues/319
=> 修改裂变系数滑块的取值范围,改为1.0~2.0

src/views/Article/index.vue
原因重复请求了两次
注释掉了评论刷新功能（原因 1.文章太长刷新就无法使用，2. 参考某乎的评论也没有做刷新评论 如果要刷新可以点击右上角的三个点或者重新进入
---
before:
---
after:
#403
=> fix 偶尔出现的重复评论

package.json, src/App.vue, src/components/ArticleCard.vue, src/views/Home/ArticlesRanking.vue, src/views/Home/ArticlesRankings.vue, src/views/Home/MyBanner.vue, src/views/Home/index.vue, src/views/User/index.vue
界面调整 文章卡片增加金额显示
---
1. 添加电报群入口
2. 调整界面 文章卡片样式
3. 增加文章卡片金额显示
4. 增加回到顶部小火箭
before:
---
after:
=> 界面调整 文章卡片增加金额显示

src/api/signature.js, src/components/ArticleCard.vue, src/views/Article/index.vue, src/views/Home/MyBanner.vue, src/views/Home/index.vue, src/views/User/index.vue
statusCode 替换为 status
因为axios 返回的是 status 不是 statusCode
=>  statusCode 替换为 status

src/components/ArticleCard.vue, src/views/User/Asset.vue
=> 文章显示时间为24小时显示  资产明细head 名称

src/store.js
=> Remove token when logout

src/views/Home/MyBanner.vue
=> 没昵称的时候显示用户名

src/common/methods.js, src/components/ArticleCard.vue, src/components/AssetCard.vue, src/components/BasePull.vue, src/views/Article/CommentsList.vue, src/views/Article/index.css, src/views/Home/ArticlesRankings.vue, src/views/User/ArticlesList.vue, src/views/User/Asset/Asset.less, src/views/User/Asset/Asset.vue, src/views/User/Asset/AssetList.vue
1. 将滚动分页组件修改为基础组件
2. 调整明细细节样式和时间显示（根据设计稿修改
=> 将滚动分页组件修改为基础组件，调整明细细节样式和时间显示

src/api/backend.js, src/assets/information.svg, src/components/BaseHeader.vue, src/store/index.js, src/views/Article/ArticleInfo.vue, src/views/Article/index.css, src/views/Article/index.vue, src/views/Home/MyBanner.vue
1. 按钮气泡提示和帮助提示
2. 文章 header 显示用户昵称
3. fix 赞赏按钮状态bug
---
=> 按钮气泡提示和帮助提示 文章 header 显示用户昵称 fix 赞赏按钮状态bug

package.json, src/main.js, src/plugins/vue-toasted.js, src/views/User/index.vue
=> 前端限制用户的昵称设置范围

src/api/backend.js, src/api/index.js, src/views/Article/Edit.vue, src/views/Article/index.vue
Remarkable! Beautiful! I can feel it humming with energy.
=> Move to get article data to beforeRouteEnter

src/api/backend.js, src/components/ArticleCard.vue, src/views/Article/index.css, src/views/Article/index.vue, src/views/Home/ArticlesRankings.vue
[文章页面头部固定&home页面上拉头部固定详情](https://andoromeda.coding.net/p/smart-signature-future/assignments/issues/117/detail)
[编辑cover修改](https://andoromeda.coding.net/p/smart-signature-future/iterations/2/affair/23)
=> 文章页面头部固定&home页面上拉头部固定&编辑cover修改

src/components/ImgUpload.vue, src/views/Publish.vue, src/views/User/DraftBox.vue, src/views/User/DraftBoxList.vue
=> 增加时间格式和修复进入草稿

src/views/Publish.vue
=> fix 更新文章，发布删除文章
